//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataKioskStacks.ValResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataKioskStacks.ValResource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Date of Birth is required.
        /// </summary>
        internal static string Date_of_Birth_is_required
        {
            get
            {
                return ResourceManager.GetString("Date_of_Birth_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name must be between 5 and 50 characters.
        /// </summary>
        internal static string First_name_is_too_short_or_too_long
        {
            get
            {
                return ResourceManager.GetString("First_name_is_too_short_or_too_long", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Firstname is required.
        /// </summary>
        internal static string Firstname_is_required
        {
            get
            {
                return ResourceManager.GetString("Firstname_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date of Birth.
        /// </summary>
        internal static string Invalid_Date_of_Birth
        {
            get
            {
                return ResourceManager.GetString("Invalid_Date_of_Birth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Local Government Area Information.
        /// </summary>
        internal static string Invalid_Local_Government_Area_Information
        {
            get
            {
                return ResourceManager.GetString("Invalid_Local_Government_Area_Information", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Marital Status.
        /// </summary>
        internal static string Invalid_Marital_Status_Information
        {
            get
            {
                return ResourceManager.GetString("Invalid_Marital_Status_Information", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Mobile Number.
        /// </summary>
        internal static string Invalid_Mobile_Number
        {
            get
            {
                return ResourceManager.GetString("Invalid_Mobile_Number", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Occupation Information.
        /// </summary>
        internal static string Invalid_Occupation_Information
        {
            get
            {
                return ResourceManager.GetString("Invalid_Occupation_Information", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Sex.
        /// </summary>
        internal static string Invalid_Sex
        {
            get
            {
                return ResourceManager.GetString("Invalid_Sex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid State of Origin Information.
        /// </summary>
        internal static string Invalid_State_Information
        {
            get
            {
                return ResourceManager.GetString("Invalid_State_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Government Area is required.
        /// </summary>
        internal static string Local_Government_Area_is_required
        {
            get
            {
                return ResourceManager.GetString("Local_Government_Area_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Marital Status Information is required.
        /// </summary>
        internal static string Marital_Status_is_required
        {
            get
            {
                return ResourceManager.GetString("Marital_Status_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mobile Number must be between 7 and 15 characters.
        /// </summary>
        internal static string Mobile_Number_must_be_between_7_and_15_characters
        {
            get
            {
                return ResourceManager.GetString("Mobile_Number_must_be_between_7_and_15_characters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Occupation is required.
        /// </summary>
        internal static string Occupation_is_required
        {
            get
            {
                return ResourceManager.GetString("Occupation_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential Address is required.
        /// </summary>
        internal static string Residential_Address_is_required
        {
            get
            {
                return ResourceManager.GetString("Residential_Address_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex Information is required.
        /// </summary>
        internal static string Sex_Info_is_required
        {
            get
            {
                return ResourceManager.GetString("Sex_Info_is_required", resourceCulture);
            }
        }

        
        /// <summary>
        ///   Looks up a localized string similar to State Information is required.
        /// </summary>
        internal static string State_Information_is_required
        {
            get
            {
                return ResourceManager.GetString("State_Information_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State of origin is required.
        /// </summary>
        internal static string State_is_required
        {
            get
            {
                return ResourceManager.GetString("State_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Surname is required.
        /// </summary>
        internal static string Surname_is_required
        {
            get
            {
                return ResourceManager.GetString("Surname_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Surname is either too short or too long.
        /// </summary>
        internal static string Surname_is_too_short_or_too_long
        {
            get
            {
                return ResourceManager.GetString("Surname_is_too_short_or_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time registered is required.
        /// </summary>
        internal static string Time_registered_is_required
        {
            get
            {
                return ResourceManager.GetString("Time_registered_is_required", resourceCulture);
            }
        }


    }
}
